[package]
name = "cargobike-provider-github"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
description = "GitHub provider implementation for Cargobike"
publish = false

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
hex = "0.4"
hmac = "0.12"
octocrab = "0.54.2"
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10"
thiserror = { workspace = true }
cargobike-core = { path = "../cargobike-core" }
